$$ \textbf{Linux and Python for Machine Learning and Data Science with IoT Examples} $$

$$\text{Scientific-Analytical Teyf Group}$$ $$\text{Seyyed Hossein Hosseini}$$

## Libraries

Installation Command:


*   `!pip install pandas`

### 3. Pandas Library



*   Pandas is a powerful and open-source Python library designed for data manipulation and analysis.

*    It provides **flexible data structures** and functions that make it easier to handle **structured data**, such as tables and time series.

*   The name "Pandas" is derived from "panel data".

*   **Question**: What kind of **data type** do we know so far?

*   Data Structures: Pandas primarily offers two **data types**(**data structures**):

    * **Series**: A one-dimensional `labeled` array capable of holding any data type(including time series)

    * **DataFrame**: A two-dimensional `labeled` data structure, similar to a table in a database or a spreadsheet, which can hold different types of data in each column

*   **Data Manipulation**: The library excels in data cleaning, merging, and reshaping. It provides tools for handling missing data, filtering rows and columns, and performing complex operations like group-by aggregations

*   **Integration with Other Libraries**: Pandas is built on top of NumPy, which allows it to leverage the power of array operations. It is often used in conjunction with other data science libraries, such as Matplotlib for visualization and Scikit-learn for machine learning

*   **File I/O**: It supports reading from and writing to various file formats, including CSV, Excel, SQL databases, and JSON, making it versatile for data import and export tasks.

**Why Pandas for IoT?**

*   **Data Handling**: IoT devices generate large volumes of time-series data, such as temperature readings, humidity levels, or sensor outputs. Pandas excels at handling such structured data, providing efficient data structures like DataFrame to store and manipulate this information.

*   **Data Analysis**: With its comprehensive set of functions for statistical analysis, aggregation, filtering, and transformation, Pandas enables developers to perform sophisticated analyses on IoT data. This can uncover trends, patterns, and insights that are crucial for decision-making in IoT applications.

*   **Time Series Analysis**: Many IoT applications involve time series data, where observations are made sequentially over time. Pandas is particularly suited for working with time series data, offering functionalities like resampling, rolling windows, and time-based indexing, which are invaluable for analyzing IoT data.

*  **Machine Learning Integration**: Pandas can be used with machine learning libraries like Scikit-learn, TensorFlow, or PyTorch, making it easy to build predictive models for IoT data.

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

In Python terminology, both Series and DataFrame are **classes** defined in the pandas library.

<p align="center">
  <img src="imgs/pandas.PNG" alt="pandas.PNG" />
</p>

#### Series

A Pandas Series is a one-dimensional labeled array capable of holding data of any type
(integer, float, string, etc.). It's similar to a column in a spreadsheet or a single
column of a DataFrame.

**Creating a Series**

In [ ]:
# Simulating temperature readings from an IoT sensor
temperature_readings = [35, 36.5, 39, 35.3, 3, 29]

# Creating a Series
temp_series = pd.Series(temperature_readings, name='Temperature')

print(temp_series)

In [ ]:
print(type(pd.Series))

In [ ]:
print(type(temp_series))

In [ ]:
print(temp_series.dtype)

In [ ]:
print(temp_series.index)

In [ ]:
print(temp_series.values)

In [ ]:
print(temp_series.shape)

In [ ]:
print(temp_series.size)

In [ ]:
print(temp_series.name)

In [ ]:
temp_series + 1.3

In [ ]:
temp_series * 2

**Adding Custom label(Index)**

In [ ]:
# In IoT applications, it's often useful to associate timestamps with sensor readings:

# Simulating temperature readings with timestamps
timestamps = ['2023-07-29 10:00', '2023-07-29 11:05', '2023-07-29 12:10',
              '2023-07-29 13:15', '2023-07-29 14:20']
temperature_readings = [29, 30.8, 31, 31.2, 32]

# Creating a Series with custom index
temp_series = pd.Series(temperature_readings, index=timestamps)

print(temp_series)

**Accessing Elements**

In [ ]:
# accessing data in a Series using index labels or integer location:

# Access by label
print(temp_series['2023-07-29 14:20'])

In [ ]:
print(temp_series[['2023-07-29 10:00', '2023-07-29 14:20']])

In [ ]:
# Access by integer location
print(temp_series.iloc[2])
print('--' * 20)
print(temp_series.iloc[1:4])

**Basic Statistics**

In [ ]:
# Pandas Series provides built-in methods for basic statistical analysis:
print("Average temperature:", temp_series.mean())
print("Maximum temperature:", temp_series.max())
print("Minimum temperature:", temp_series.min())
print("Median temperature:", temp_series.median())
print("Standard Deviation:", temp_series.std())
print("Variance:", temp_series.var())

In [ ]:
temp_series.describe()

**Filtering Data**

In [ ]:
# filtering data based on conditions:

# Temperatures above 29°C
high_temps = temp_series[temp_series > 29]
print("High temperatures:")
print(high_temps)

In [ ]:
la_temps = temp_series[temp_series > temp_series.mean()]
print(la_temps)

**Visualization**

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(3, 3))
temp_series.plot()
plt.title('Temperature Readings Over Time', fontsize=10)
plt.xlabel('Time')
plt.ylabel('Temperature (°C)')
plt.show()

#### DataFrame

<p align="center">
  <img src="imgs/dataframe.PNG" alt="dataframe.PNG" />
</p>

Pandas DataFrame is a powerful data structure(data type) in Python for storing and working with **tabular data**.

**Creating a DataFrame**

In [ ]:
iot_data = {
    'device_id': ['dev001', 'dev002', 'dev003', 'dev001', 'dev004'],
    'timestamp': ['2024-07-30 10:00:00', '2024-07-30 11:01:00', '2024-07-30 12:02:00',
                  '2024-07-30 16:03:00', '2024-07-30 17:03:00'],
    'temperature': [28.5, 29.2, 32.8, 28.7, 28],
    'humidity': [18, 17, 16, 17.8, 19]
}

df = pd.DataFrame(iot_data)
print(df)

In [ ]:
print(type(pd.DataFrame))

In [ ]:
print(type(df))

**ًQuestion**: Why don't we work with the dictionary itself?

Attributes and methods provide essential functionality for working with DataFrames, including data inspection, manipulation, analysis, and export. They allow you to perform a wide range of operations on your data efficiently

**Common Attributes of the Created DataFrame(Object):**

In [ ]:
df.dtype

In [ ]:
df.dtypes

In [ ]:
df.index

In [ ]:
df.values

In [ ]:
type(df.values)

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
nrows, ncols = df.shape
print(f"Number of Samples: {nrows}\nNumber of Features: {ncols}")

In [ ]:
print(f"Number of Samples: {nrows}\tNumber of Features: {ncols}")

**Common Methods of the Created DataFrame(Object):**

In [ ]:
df.head(2)

In [ ]:
df.tail(3)

In [ ]:
df.info()

**Basic Statistics**

In [ ]:
# providing a quick overview of data's distribution(descriptive statistics of a DataFrame)
df.describe()






*   **25% (First Quartile, Q1)**: This is the value below which 25% of the observations fall. It's also known as the lower quartile.

*   **50% (Second Quartile, Median, Q2)**: This is the middle value of the dataset; half the data falls below this value and half above. It's the most commonly cited measure of central tendency.

*   **75% (Third Quartile, Q3)**: This is the value below which 75% of the observations fall. It's also known as the upper quartile.


*    Pandas uses interpolation to calculate quartiles, which can lead to slightly different results compared to traditional statistical definitions, especially for datasets with an even number of observations.

In [ ]:
df.describe(include=['object'])

**Accessing Elements**

In [ ]:
df

In [ ]:
df["temperature"]  # or df.temperature

In [ ]:
print(type(df["temperature"]))

In [ ]:
df[["temperature"]]

In [ ]:
print(type(df[["temperature"]]))

1. Method df.iloc[ ]

In [ ]:
help(df.iloc)

In [ ]:
# df.iloc[rows_numbers, columns_numbers]
# integer, integer slice (START point is INCLUDED, END point is EXCLUDED), list of integers, and boolean array
df.iloc[0, 0]

In [ ]:
df.iloc[1, 3]

In [ ]:
df.iloc[:3, :]

In [ ]:
df.iloc[:3, 2:]

In [ ]:
df.iloc[-3:,[2,-1]]

In [ ]:
df.iloc[[True,False,True,False,False],[0, 1, 3]]

In [ ]:
df.iloc[[True,False,True,False,False], :]

2. Method df.loc[ ]

In [ ]:
df

In [ ]:
# df.loc[rows_label, columns_labe]
df.loc[2, "humidity"]

In [ ]:
df.loc[[0, 2, 4], ["device_id", "humidity"]]

In [ ]:
# when using slicing with df.loc[], the end of the slice is inclusive.
df.loc[1:4, "timestamp":"humidity"]

In [ ]:
df.loc[[True,False,True,False,False],[True, False, True, False]]

In [ ]:
df.loc[[True,False,True,False,False], :]

**Filtering Data**

In [ ]:
s = df["temperature"] > 28.8
print(s)

In [ ]:
print(type(s))

In [ ]:
df_2 = df[df["temperature"]>28.8]
print(df_2)

In [ ]:
print(type(df_2))

**Question**: Why do we need to know type of the objects?

**Visualization**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Line Plot of Temperature and Humidity over Time:
plt.figure(figsize=(6, 4))
plt.plot(df['timestamp'], df['temperature'], label='Temperature')
plt.plot(df['timestamp'], df['humidity'], label='Humidity')
plt.xlabel('Timestamp')
plt.ylabel('Value')
plt.title('Temperature and Humidity over Time')
plt.legend()
plt.grid()
plt.xticks(rotation=45, fontsize=7)
plt.tight_layout()
plt.show()

In [ ]:
# Line Plot of Temperature vs. Humidity:
plt.figure(figsize=(6, 3))
sns.lineplot(data=df, x='temperature', y='humidity')
plt.title('Temperature vs. Humidity')
plt.show()

In [ ]:
# Scatter Plot of Temperature vs. Humidity:
plt.figure(figsize=(6, 3))
sns.scatterplot(data=df, x='temperature', y='humidity', hue='device_id')
plt.title('Temperature vs. Humidity by Device')
plt.show()

Pearson Correlation Coefficient



*   Pearson’s correlation coefficient(r) is a widely used metric for assessing linear relationships between two random variables
*   In the Context of DataFrames:
    * When we use .corr() on a DataFrame, each column is treated as a realization of a random variable.
    * The method calculates the sample correlation coefficient, which is an **estimate** of the population
    correlation coefficient.

*   Sample vs. Population:

    * In practice, we usually work with sample data, so we calculate the sample Pearson correlation coefficient(r).
    * This is an estimate of the population correlation coefficient(ρ).

*   Assumptions:

    * The Pearson correlation assumes that the relationship between the variables is linear.
    * It also assumes that the variables are normally distributed (for inferential purposes).


*   Interpretation:

    * The coefficient ranges from -1 to 1.
    * A value of 1 implies that a linear equation perfectly describes the relationship between X and Y, with all data points lying on a line for which Y increases as X increases.
    * A value of −1 implies that all data points lie on a line for which Y decreases as X increases.
    * A value of 0 implies that there is no linear correlation between the variables(**uncorrelated**)

* Formula:

<p align="center">
  <img src="imgs/correlation_coefficient.PNG" alt="correlation_coefficient.PNG" />
</p>

In [ ]:
# Heatmap of Correlation between Temperature and Humidity:
# Calculating the correlation matrix:
# By default, .corr() uses the Pearson correlation coefficient, which measures the linear correlation between two random variables
# corr() method to compute the correlation matrix.
# By default, it computes the Pearson correlation coefficient, but other methods like Spearman
# and Kendall can also be used depending on the nature of the data.
# the .corr() method in pandas DataFrames is used to compute the pairwise correlation of columns

plt.figure(figsize=(5, 3))
correlation_matrix = df[['temperature', 'humidity']].corr(method='pearson')
print(correlation_matrix)

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.1f')
plt.title('Correlation Heatmap: Temperature vs. Humidity', fontsize=10)
plt.show()

**Working with Datasets**

How to Write and Read Tabular Data

<p align="center">
  <img src="imgs/read_write_Pandas.PNG" alt="read_write_Pandas" />
</p>

**Write**

In [ ]:
df

In [ ]:
# Writing the DataFrame object into a comma-separated values (csv) file by to_csv() / to_excel() method
df.to_csv('/content/drive/MyDrive/Projects/Python/datasets/iot_data.csv')

In [ ]:
# to_excel() method is a powerful tool for exporting data from pandas DataFrames to Excel
df.to_excel('/content/drive/MyDrive/Projects/Python/datasets/iot_data.xlsx', sheet_name='MySheet', index=False, header=True)

In [ ]:
# Example with Custom Options
df.to_csv('/content/drive/MyDrive/Projects/Python/datasets/iot_data_2.csv', index=False,
          sep='\t', header=True, columns=['device_id', 'humidity'])

Performance: For very large DataFrames, writing to Excel files can be slower compared to other formats like CSV due to the overhead associated with the Excel file format. If performance is a concern, consider using compressed CSV files or alternative storage solutions.

**Dataset**

[Knowing about dataset](https://www.kaggle.com/datasets/jainaru/electric-vehicle-population)

**Download**

Downloading Kaggle datasets to Colab environment without manually downloading and uploading files

In [ ]:
!pip install kaggle

In [ ]:
!mkdir ~/.kaggle

In [ ]:
!cp /content/drive/MyDrive/Projects/Python/kaggle.json ~/.kaggle/

In [ ]:
# The chmod 600 command sets the permissions so that only the owner can read and write the file, which is important for security.
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download jainaru/electric-vehicle-population

In [ ]:
!unzip /content/electric-vehicle-population.zip -d /content/drive/MyDrive/Projects/Python/datasets

**Read**

In [ ]:
# pandas provides the read_csv() function to read data stored as a csv file into a pandas DataFrame.
df = pd.read_csv('/content/drive/MyDrive/Projects/Python/datasets/Electric_Vehicle_Population_Data.csv')

**Analyzing Data**

In [ ]:
print(type(df))

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
# DataFrame.describe(percentiles=None, include=None, exclude=None)
df.head()

In [ ]:
df.tail()

In [ ]:
df.sample(3)

In [ ]:
df.nunique()

In [ ]:
df.info()

In [ ]:
# DataFrame.describe(percentiles=None, include=None, exclude=None)
df.describe()

In [ ]:
df.describe(percentiles=[0.1, 0.2, .8])

In [ ]:
df.iloc[0:3, :7]

In [ ]:
df.loc[0:7, ["Make", "Model", "Electric Range"]]

In [ ]:
df_3 = df[df["Electric Range"] > 75]
print(df_3.shape[0])

In [ ]:
df.set_index('VIN (1-10)', inplace=True)

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.shape

In [ ]:
df.rename(columns = lambda col: col.upper())

In [ ]:
df

In [ ]:
df.rename(columns= {'Make': 'Manufacturer'}, inplace=True)
# or df = df.rename(columns= {'Make': 'Manufacturer'})

In [ ]:
df.head()

In [ ]:
df.reset_index(inplace=True)
df

In [ ]:
df.index

In [ ]:
df['Make'].unique()

In [ ]:
df['Manufacturer']

In [ ]:
len(df['Manufacturer'])

In [ ]:
df['Manufacturer'].unique()

In [ ]:
df['Manufacturer'].value_counts()

In [ ]:
df[['Manufacturer', 'Model Year']].value_counts()

Manufacturer  Model Year
TESLA         2023          28609
              2022          13773
              2021          11005
              2018           7918
              2020           7070
                            ...
MAZDA         2023              1
BENTLEY       2021              1
MITSUBISHI    2017              1
ROLLS ROYCE   2024              1
TOYOTA        2003              1
Name: count, Length: 255, dtype: int64

In [ ]:
print(type(df[['Manufacturer', 'Model Year']].value_counts()))

<class 'pandas.core.series.Series'>

In [ ]:
# transforming to DataFrame
df[['Manufacturer', 'Model Year']].value_counts().reset_index()

    Manufacturer  Model Year  count
0          TESLA        2023  28609
1          TESLA        2022  13773
2          TESLA        2021  11005
3          TESLA        2018   7918
4          TESLA        2020   7070
..           ...         ...    ...
250        MAZDA        2023      1
251      BENTLEY        2021      1
252   MITSUBISHI        2017      1
253  ROLLS ROYCE        2024      1
254       TOYOTA        2003      1

[255 rows x 3 columns]

In [ ]:
print(type(df[['Manufacturer', 'Model Year']].value_counts().reset_index()))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df[['Manufacturer', 'Model Year']].value_counts().reset_index()
# interactive table

In [ ]:
df['Manufacturer'].describe()

In [ ]:
# adding new column
df["Number"] = 1

In [ ]:
df.head()

In [ ]:
df.sort_values(by='Model Year', ascending=False)

Filtering

In [ ]:
df[df['Manufacturer'] == 'TESLA']

In [ ]:
# negation
df[~(df['Manufacturer'] == 'TESLA')]

In [ ]:
df[(df['Manufacturer'] == 'TESLA') & (df['Model Year'] == 2024)]

In [ ]:
df[(df['Manufacturer'] == 'TESLA') | (df['Model Year'] == 2024)]

In [ ]:
df[df["Electric Range"] >= 100]

Handling missing data (null values)

In [ ]:
# Pandas represents missing data as NaN (Not a Number)
# Counting Missing Values
df.isna().sum()

VIN (1-10)                                             0
County                                                 3
City                                                   3
State                                                  0
Postal Code                                            3
Model Year                                             0
Manufacturer                                           0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 398
DOL Vehicle ID                                         0
Vehicle Location                                       8
Electric Utility                                       3
2020 Census Tract                                      3
Number                                                 0
dtype: int64

1. Removing Missing Values

*    dropna(): Removes rows or columns containing missing values.

In [ ]:
# To remove rows with any missing values:
df_cleaned = df.dropna(axis=0)

In [ ]:
df_cleaned.isna().sum()

VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
Postal Code                                          0
Model Year                                           0
Manufacturer                                         0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Base MSRP                                            0
Legislative District                                 0
DOL Vehicle ID                                       0
Vehicle Location                                     0
Electric Utility                                     0
2020 Census Tract                                    0
Number                                               0
dtype: int64

In [ ]:
df.shape

(181458, 18)

In [ ]:
df_cleaned.shape

(181055, 18)

In [ ]:
# To remove columns with any missing values:
df_cleaned_2 = df.dropna(axis=1)

In [ ]:
df_cleaned_2.shape

(181458, 11)

In [ ]:
df_cleaned_3 = df.dropna(subset=['Electric Utility'])

In [ ]:
df_cleaned_3.shape

(181455, 18)

2. Filling Missing Values

*   fillna(): Replaces missing values with a specified value or method.

In [ ]:
# Fill with a constant value:
df_filled = df.fillna(value=0)

In [ ]:
# Forward fill (propagate last valid observation forward):
df_filled = df.fillna(method='ffill')

In [ ]:
# Backward fill (use next valid observation to fill gap):
df_filled = df.fillna(method='bfill')

In [ ]:
# Fill with mean, median, or mode of the column:
mode = df['City'].mode()
print(mode)
print(type(mode))

0    Seattle
Name: City, dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
mode_value = mode[0]
print(mode_value)

Seattle

In [ ]:
# Fill with mean, median, or mode of the column:
df['City'] = df['City'].fillna(mode_value)

In [ ]:
# concise form
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [ ]:
df.isna().sum()

VIN (1-10)                                             0
County                                                 3
City                                                   0
State                                                  0
Postal Code                                            3
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 398
DOL Vehicle ID                                         0
Vehicle Location                                       8
Electric Utility                                       3
2020 Census Tract                                      3
dtype: int64

3. Interpolating Missing Values

*    interpolate(): Interpolates missing values linearly or with other methods.

In [ ]:
# df['Electric Range'] = df['Electric Range'].interpolate(method='polynomial', order=2)

4. Using apply() for Custom Null Handling

In [ ]:
def custom_fillna(series):
    ....
    ....
    return ....

df_custom_filled = df.apply(custom_fillna)



*   Choosing the right strategy depends on the nature of your data and the specific requirements of your analysis.
*   Always consider the implications of removing or imputing missing values, as these decisions can significantly affect your results.

Aggregation Functions

*    Pandas offers a wide range of aggregation functions(min, max, mean, median, var, std, sum, ...) that can be applied to groups of data.

*    An aggregation function processes a set of values to produce a single summary value.

In [ ]:
print(df['Electric Range'].min())
print(df['Electric Range'].max())
print(df['Electric Range'].mean())
print(df['Electric Range'].median())
print(df['Electric Range'].var())
print(df['Electric Range'].std())
print(df['Electric Range'].sum())
print(df['Electric Range'].quantile([0.6, 0.8]))

0
337
57.82666512360987
0.0
8353.242305880362
91.39607379904436
10493111
0.6     25.0
0.8    125.0
Name: Electric Range, dtype: float64

In [ ]:
df[['Electric Range', 'Model Year']].agg(['min', 'max', 'mean', 'std'])

In [ ]:
# Custom Aggregation Functions
df[['Electric Range', 'Model Year', 'Model']].agg(
    {'Electric Range': ['min', 'max', 'mean', 'std'],
    'Model Year': 'mean',
    'Model': 'mode'})

     Electric Range   Model Year    Model
     Electric Range   Model Year     mode
min        0.000000          NaN      NaN
max      337.000000          NaN      NaN
mean      57.826665  2020.581793      NaN
std       91.396074          NaN      NaN
0               NaN          NaN  MODEL Y

In [ ]:
def custom_agg_func(group):
    return group.sum() / group.count()

df[['Electric Range']].agg(custom_agg_func)

Electric Range    57.826665
dtype: float64

These aggregation functions form the backbone of many data analysis workflows in Pandas, allowing for efficient summarization and exploration of large datasets.

Query

In [ ]:
df[df['Electric Range']>320]

In [ ]:
df.query('Electric Range > 320')

In [ ]:
df.rename(columns={'Electric Range': 'Range'}, inplace=True)

In [ ]:
df.query('Range > 320')

In [ ]:
df.query('Range > 320 and Make == "TESLA" ')

GroupBy

*    The groupby method allows users to split data into groups, apply a function to each group independently, and then combine the results.

*    This process is often referred to as the "split-apply-combine" strategy.

In [ ]:
# Sample DataFrame representing IoT telecom data
data = {
    'DeviceID': ['device1', 'device2', 'device1', 'device2', 'device1', 'device2', 'device1', 'device1'],
    'DataType': ['temperature', 'humidity', 'pressure', 'temperature', 'humidity', 'pressure', 'temperature', 'pressure'],
    'DataUsageMB': [10, 15, 20, 25, 30, 35, 40, 45]  # Data usage in megabytes
}

df_IoT = pd.DataFrame(data)
print("Original IoT Telecom Data:")
print(df_IoT)

# Group by 'DeviceID' and aggregate the sum of 'DataUsageMB'
result = df_IoT.groupby('DeviceID')['DataUsageMB'].sum()

print("\n\nTotal Data Usage by each Device:")
print(result)

Original IoT Telecom Data:
  DeviceID     DataType  DataUsageMB
0  device1  temperature           10
1  device2     humidity           15
2  device1     pressure           20
3  device2  temperature           25
4  device1     humidity           30
5  device2     pressure           35
6  device1  temperature           40
7  device1     pressure           45


Total Data Usage by each Device:
DeviceID
device1    145
device2     75
Name: DataUsageMB, dtype: int64

In [ ]:
# calculating the mean of the 'Range' column for each unique value in the 'Make' column of df
df.groupby('Make')['Range'].mean()

In [ ]:
df.groupby('Make')['Range'].mean().sort_values(ascending=False)

In [ ]:
df.groupby('Make')['Range'].agg(['min', 'max', 'mean', 'std'])

In [ ]:
# multiple columns for grouping
# first group by 'Make', then within each group, group by 'Model' and calculate the mean of 'Range'
df.groupby(['Make', 'Model'])['Range'].mean()

In [ ]:
print(type(df.groupby(['Make', 'Model'])['Range'].mean()))

<class 'pandas.core.series.Series'>

In [ ]:
df.groupby(['Make', 'Model'])['Range'].mean()

In [ ]:
df.groupby(['Make', 'Model'])['Range'].mean().reset_index()

In [ ]:
print(type(df.groupby(['Make', 'Model'])['Range'].mean().reset_index()))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# Apply a custom function to each group
def custom_function(group):
    return group['Range'].mean()

df.groupby('Make').apply(custom_function)



*   The groupby method in Pandas is versatile and powerful, enabling a wide range of data manipulations and analyses.
*   Whether you're aggregating data, applying custom functions to groups, or exploring relationships between variables, groupby is a fundamental tool in the Pandas library.

Pivot Table

*   Pandas provides methods for manipulating a Series and DataFrame to alter the **representation** of the data for further data processing or data summarization.

In [ ]:
# Sample telecom IoT data
data = {
    'DeviceID': ['Device1', 'Device1', 'Device2', 'Device3', 'Device1', 'Device2', 'Device3'],
    'Region': ['North', 'North', 'South', 'East', 'West', 'North', 'South'],
    'DataUsageMB': [500, 1000, 2000, 1500, 3000, 2500, 3500],
    'Month': ['Jan', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
}
df_1 = pd.DataFrame(data)

print(df_1)

# Pivot table to get average data usage per device per month across different regions
# This gives insights into how much data each device is using on average in each region over time.
pivot_df = df_1.pivot_table(index=['DeviceID', 'Month'], columns='Region', values='DataUsageMB', aggfunc='mean')

print(f'\n\n {pivot_df}')

  DeviceID Region  DataUsageMB Month
0  Device1  North          500   Jan
1  Device1  North         1000   Jan
2  Device2  South         2000   Feb
3  Device3   East         1500   Mar
4  Device1   West         3000   Apr
5  Device2  North         2500   May
6  Device3  South         3500   Jun


 Region            East   North   South    West
DeviceID Month
Device1  Apr       NaN     NaN     NaN  3000.0
         Jan       NaN   750.0     NaN     NaN
Device2  Feb       NaN     NaN  2000.0     NaN
         May       NaN  2500.0     NaN     NaN
Device3  Jun       NaN     NaN  3500.0     NaN
         Mar    1500.0     NaN     NaN     NaN

In [ ]:
pivot_df_ev = df.pivot_table(index=['Make', 'Model'], columns='Electric Vehicle Type', values='Electric Range', aggfunc='mean')
pivot_df_ev.shape
pivot_df_ev.to_excel('pivot_df_ev.xlsx')

In [ ]:
# defining custom aggregation functions
pivot_df_ev_custom = df.pivot_table(index=['Make', 'Model'], columns='Electric Vehicle Type', values='Electric Range', aggfunc=lambda x: x.sum() + x.mean())
pivot_df_ev_custom.to_excel('pivot_df_ev_custom.xlsx')

In [ ]:
# calculating Multiple Values
pivot_df_ev_multiple_values = df.pivot_table(index=['Make', 'Model'], columns='Electric Vehicle Type',
                                             values=['Electric Range', 'Model Year'],
                                             aggfunc={'Electric Range': 'mean', 'Model Year': 'min'}
                                             )
pivot_df_ev_multiple_values.to_excel('pivot_df_ev_multiple.xlsx')

**Key Differences between GroupBy and Pivot Table**

*   **Shape of Output**: groupby results in a long, stacked format, while pivot_table results in a wide, matrix-like format.
*   **Complexity**: pivot_table can handle more complex data transformations by allowing multiple levels of aggregation and cross-tabulation, whereas groupby is more straightforward and linear.

Combining DataFrames

In [ ]:
df_1 = df[df['Make'] == 'TESLA']
df_2 = df[df['Make'] == 'BMW']

print(f'df_1 shape: {df_1.shape}')
print(f'\ndf_2 shape: {df_2.shape}')

df_1 shape: (80819, 17)

df_2 shape: (7680, 17)

In [ ]:
df_3 = pd.concat([df_1, df_2], axis=0)
df_3

In [ ]:
print(f'df_3 shape: {df_3.shape}')

df_3 shape: (88499, 17)

In [ ]:
df_4 = pd.concat([df_1, df_2], axis=1)
df_4

In [ ]:
df_4.shape

(88499, 34)

#### Data Visualization

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# distribution of manufacturers
manufacturer = df["Manufacturer"].value_counts().head(5)
plt.figure(figsize=(6, 4))
# plt.style.use('ggplot')  # Using ggplot style for a modern look
ax = manufacturer.plot(kind='bar', color=['gold', 'silver', 'blue', 'green', 'red'])
ax.set_title('Top 5 Manufacturers Distribution', fontsize=10)
ax.set_xlabel('Manufacturers', fontsize=10)
ax.set_ylabel('Count', fontsize=10)
plt.xticks(rotation=0)

# Adding value labels above bars
for p in ax.patches:
    width = p.get_width()
    height = p.get_height()
    x, y = p.get_xy()
    ax.annotate(f'{height:.0f}', (x + width / 2, y + height*1.02), ha='center')

plt.show()

In [ ]:
# distribution of cities
city = df["City"].value_counts().head(5)
plt.figure(figsize=(6, 4))
plt.style.use('ggplot')  # Using ggplot style for a modern look
ax = city.plot(kind='bar', color=['gold', 'silver', 'blue', 'green', 'red'])
ax.set_title('Top 5 Cities Distribution', fontsize=10)
ax.set_xlabel('Cities', fontsize=10)
ax.set_ylabel('Count', fontsize=10)
plt.xticks(rotation=45)

# Adding value labels above bars
for p in ax.patches:
    width = p.get_width()
    height = p.get_height()
    x, y = p.get_xy()
    ax.annotate(f'{height:.0f}', (x + width/2, y + height*1.02), ha='center')

plt.show()

In [ ]:
# distribution of manufacturers in Seattle
seattle_data = df[df["City"] == "Seattle"]
manufacturer = seattle_data["Manufacturer"].value_counts().head(5)


plt.figure(figsize=(6, 4))
plt.style.use('ggplot')  # Using ggplot style for a modern look
ax = manufacturer.plot(kind='bar', color=['gold', 'silver', 'blue', 'green', 'red'])
ax.set_title('Top 5 Best-Selling Cars at Seattle', fontsize=10)
ax.set_xlabel('Manufacturers', fontsize=10)
ax.set_ylabel('Count', fontsize=10)
plt.xticks(rotation=0)

# Adding value labels above bars
for p in ax.patches:
    width = p.get_width()
    height = p.get_height()
    x, y = p.get_xy()
    ax.annotate(f'{height:.0f}', (x + width/2, y + height*1.02), ha='center')

plt.show()

In [ ]:
# distribution of electric vehicle types
plt.figure(figsize=(6, 2))
ax = sns.countplot(y='Electric Vehicle Type', hue='Electric Vehicle Type', data=df, palette='magma')
plt.title('Distribution of Electric Vehicle Types', fontsize=11)
plt.xlabel('Count')
plt.ylabel('Electric Vehicle Type')

# Add value labels to the bars
for i in ax.containers:
    ax.bar_label(i)

plt.show()

In [ ]:
# count of Vehicles by Model Year
plt.figure(figsize=(8, 4))
sns.countplot(x='Model Year', data=df)
plt.title('Count of Vehicles by Model Year')
plt.xlabel('Model Year')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

In [ ]:
# electric range distribution
plt.figure(figsize=(7, 4))
sns.histplot(df['Electric Range'], bins=40, color='purple')
plt.title('Distribution of Electric Range')
plt.xlabel('Electric Range')
plt.ylabel('Frequency')
plt.show()

#### Another Example

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Simulating temperature data
np.random.seed(42)
rooms = ['Room A', 'Room B', 'Room C', 'Room D']
hours = [f'Hour {i}' for i in range(1, 7)]
data = np.random.randint(18, 30, size=(len(hours), len(rooms)))
df = pd.DataFrame(data, columns=rooms, index=hours)

# Creating heatmap
plt.figure(figsize=(6, 3))
sns.heatmap(df, annot=True, fmt="d", cmap='coolwarm', linewidths=.5)
plt.title('Temperature Variations Across Rooms Over Time')
plt.show()

#### Memory Management and Speed Optimization

*  **Memory Management**

  * **1. Use Memory-Efficient Data Structures**: Instead of using large data structures, opt for more memory-efficient ones. For instance, consider using NumPy arrays instead of Pandas DataFrames if you don't need the additional functionality provided by Pandas.

  * **2. Optimize Data Loading**: Load only necessary data into memory. If you're dealing with large datasets, use Pandas' read_csv() with parameters like **usecols** to load only specific columns.

  *  **3. Garbage Collection**: Python's garbage collector can be manually invoked to free up memory. Use **gc.collect()** to clean up unused objects.

  *  **4. Data Types Optimization**: Use the appropriate data types for your DataFrame columns. For example, use astype('category') for columns with a limited number of unique values.



* **Speed Optimization**

  *  **1. Vectorization**: Use Pandas' built-in vectorized operations instead of looping through DataFrame rows. This can significantly speed up data manipulation tasks.

  *  **2. Use of Efficient Libraries**: Libraries like NumPy and Pandas are optimized for performance. Ensure you're using the latest versions to benefit from performance improvements.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181458 entries, 0 to 181457
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         181458 non-null  object
 1   County                                             181455 non-null  object
 2   City                                               181455 non-null  object
 3   State                                              181458 non-null  object
 4   Postal Code                                        181455 non-null  float64
 5   Model Year                                         181458 non-null  int64
 6   Make                                               181458 non-null  object
 7   Model                                              181458 non-null  object
 8   Electric Vehicle Type                              181458 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  181458 non-null  object
 10  Electric Range                                     181458 non-null  int64
 11  Base MSRP                                          181458 non-null  int64
 12  Legislative District                               181060 non-null  float64
 13  DOL Vehicle ID                                     181458 non-null  int64
 14  Vehicle Location                                   181450 non-null  object
 15  Electric Utility                                   181455 non-null  object
 16  2020 Census Tract                                  181455 non-null  float64
dtypes: float64(3), int64(4), object(10)
memory usage: 23.5+ MB

In [ ]:
df_1 = pd.read_csv('/content/drive/MyDrive/Projects/Python/datasets/Electric_Vehicle_Population_Data.csv',
                 usecols=['Make', 'Model', 'Electric Range'])

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181458 entries, 0 to 181457
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Make            181458 non-null  object
 1   Model           181458 non-null  object
 2   Electric Range  181458 non-null  int64
dtypes: int64(1), object(2)
memory usage: 4.2+ MB

In [ ]:
import gc

# Load and process a large dataset
df = pd.read_csv('/content/drive/MyDrive/Projects/Python/datasets/Electric_Vehicle_Population_Data.csv')

# Perform operations on df
# ...

# After finishing with the DataFrame, manually invoke the garbage collector
gc.collect()

0

In [ ]:
# data types optimization
df['City'] = df['City'].astype('category')
df['County'] = df['County'].astype('category')
df['State'] = df['State'].astype('category')
df['Model'] = df['Model'].astype('category')
df['Model Year'] = df['Model Year'].astype('int16')
df['Electric Range'] = df['Electric Range'].astype('int16')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181458 entries, 0 to 181457
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         181458 non-null  object
 1   County                                             181455 non-null  category
 2   City                                               181455 non-null  category
 3   State                                              181458 non-null  category
 4   Postal Code                                        181455 non-null  float64
 5   Model Year                                         181458 non-null  int16
 6   Make                                               181458 non-null  object
 7   Model                                              181458 non-null  category
 8   Electric Vehicle Type                              181458 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  181458 non-null  object
 10  Electric Range                                     181458 non-null  int16
 11  Base MSRP                                          181458 non-null  int64
 12  Legislative District                               181060 non-null  float64
 13  DOL Vehicle ID                                     181458 non-null  int64
 14  Vehicle Location                                   181450 non-null  object
 15  Electric Utility                                   181455 non-null  object
 16  2020 Census Tract                                  181455 non-null  float64
dtypes: category(4), float64(3), int16(2), int64(2), object(6)
memory usage: 17.2+ MB